config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/about', to: 'application#about', as: 'about'
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
   # if user.admin?
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	validates_presence_of :image

	mount_uploader :image, PhotoUploader
	before_create :init_time
	before_update :init_update_time
	Categories = [["轮播图",0],["小图",1]]

	def init_time
		self.created_at = Time.now
		self.updated_at = Time.now
	end

	def init_update_time
		self.updated_at = Time.now
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  ROLES = %i[admin author]

  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    roles.include?(role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home, :about, :contact]

  def home
    photos = Photo.all.limit(20)
    @scrolls = photos.where(:img_type => 0)
    @thums = photos.where(:img_type => 1)
  end

  def about

  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, roles: []])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :created_at, :updated_at,:img_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'Role was successfully updated.' }
        format.json { render :index, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(roles: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <p>#{sentence}</p>
    <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/post_helper.rb
module PostHelper
  def format_timestamp(ts,format='%Y-%m-%d %H:%M')
    Time.at(ts).strftime(format)
  end
end

app/views/application/about.html.slim
= content_for :title do
  = 'About'

.text-center
  h5 《乱入！Sonkwo形象补全计划 - 杉果吉祥物征集大赛》 <small>优秀方案奖</small>
  hr
    img src ="/uploads/photo/image/detail.jpg" class="img-responsive center-block"
    img src ="/uploads/photo/image/detail_02.jpg" class="img-responsive center-block"
    img src ="/uploads/photo/image/detail_03.jpg" class="img-responsive center-blockgit"

app/views/application/home.html.slim
.home
  .carousel.slide id="carousel-generic" data-ride="carousel"
    ol class="carousel-indicators"
      //- @scrolls.length().times do |i|
        li data-target="#carousel-generic" data-slide-to="#{i}"
      li data-target="#carousel-generic" data-slide-to="0"
      li data-target="#carousel-generic" data-slide-to="1"
      li data-target="#carousel-generic" data-slide-to="2"
    .carousel-inner role="listbox"
      - for item in @scrolls
        .item
          img src= item.image
            .carousel-caption

    a href="#carousel-generic" class="left carousel-control" role="button" data-slide="prev"
      span class="glyphicon glyphicon-chevron-left" aria-hidden="true"
    a href="#carousel-generic" class="right carousel-control" role="button" data-slide="next"
      span class="glyphicon glyphicon-chevron-right" aria-hidden="true"
hr
.row
  - for item in @thums
    .col-xs-6.col-md-4
      .thumbnail
        img src= item.image

app/views/layouts/_navigation.html.slim
ul class="nav navbar-nav"
  li= link_to('<span class="glyphicon glyphicon-home"></span> 首页'.html_safe, root_path)
  li= link_to('<span class="glyphicon glyphicon-comment"></span> 设计说明'.html_safe, about_path)
  - if can?(:manager,current_user)
    li= link_to('<span class="glyphicon glyphicon-picture"></span> 图片管理'.html_safe, photos_path)
    li= link_to('<span class="glyphicon glyphicon-user"></span> 用户管理'.html_safe, users_path)



ul class="nav navbar-nav navbar-right"
  - if current_user
    li= link_to('<span class="glyphicon glyphicon-cog"></span> 设置'.html_safe, edit_user_registration_path)
    li= link_to('<span class="glyphicon glyphicon-off"></span> 注销'.html_safe, destroy_user_session_path, method: 'delete')
  - else
    li= link_to('<span class="glyphicon glyphicon-log-in"></span> 登陆'.html_safe, new_user_session_path)
    li= link_to('<span class="glyphicon glyphicon-saved"></span> 注册'.html_safe, new_user_registration_path)

app/views/layouts/_notifications.html.slim
- if notice
  .alert.alert-info
    p= notice

- if alert
  .alert.alert-warning
    p= alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= content_for?(:title) ? yield(:title) + " - #{APPLICATION_NAME}" : "#{APPLICATION_NAME}" %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>
  </head>
  <body>
	  <nav class="navbar navbar-default">
		  <div class="container-fluid">
			  <div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed"
				          data-toggle="collapse" data-target="#menu-collapse">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
				  </button>
				  <%= link_to APPLICATION_NAME, root_path, class: 'navbar-brand' %>
			  </div>

			  <div class="collapse navbar-collapse" id="menu-collapse">
				  <%= render 'layouts/navigation' %>
			  </div>


		  </div>
	  </nav>

	  <div class="container">
		  <%= render 'layouts/notifications' %>

      <%= yield %>
	  </div>



  </body>
</html>

app/views/photos/_form.html.slim
= form_for @photo do |f|
  - if @photo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      ul
        - @photo.errors.full_messages.each do |message|
          li = message
  .row
    .col-lg-offset-3.col-lg-6.col-md-offset-3.col-md-6.col-sm-offset-2.col-sm-8.col-xs-12
      .panel.panel-default
        .panel-body


          .form-group
            = f.file_field(:image,required: "true")
            p class="help-block" 注意上传格式
          .form-group
            = f.select(:img_type,Photo::Categories, class: 'form-control')
          = f.submit('提交', class: 'btn btn-default  q')

app/views/photos/edit.html.slim
h1 Editing photo

== render 'form'

= link_to 'Show', @photo
'|
= link_to 'Back', photos_path

app/views/photos/index.html.slim
table class = "table table-condensed"
  thead
    tr
      th Images
      th 创建时间
      th 类型
      th
      th
      th

  tbody
    - @photos.each do |photo|
      tr
        td
          img src = photo.image class = "img-rounded"
        td = format_timestamp(photo.created_at,'%Y-%m-%d %H:%M')
        td = photo.img_type
        - if can?(:manager,photo)
          td = link_to 'Show', photo
          td = link_to 'Edit', edit_photo_path(photo)
          td = link_to 'Destroy', photo, data: { confirm: 'Are you sure?' }, method: :delete
= link_to 'New Photo', new_photo_path, :class => "btn btn-default" if can?(:manager,@user)

app/views/photos/show.html.slim
p#notice = notice

p
  strong Image:
  = @photo.image
p
  strong Created at:
  = @photo.created_at
p
  strong Updated at:
  = @photo.updated_at

= link_to 'Edit', edit_photo_path(@photo)
'|
= link_to 'Back', photos_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  .row
    .col-lg-offset-3.col-lg-6.col-md-offset-3.col-md-6.col-sm-offset-2.col-sm-8.col-xs-12
      .panel.panel-default
        .panel-body
          h5 权限设置
          .form-group
            - for role in User::ROLES
              = check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {:name => "user[roles][]"}
              = label_tag "user_roles_#{role}", role.to_s.humanize

          = f.submit('提交', class: 'btn btn-default')

app/views/users/edit.html.slim
== render 'form'

app/views/users/index.html.slim
table class = "table table-condensed"
  thead
    tr
      th id
      th email
      th role


  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.email
        td = user.roles.try(:first)
        - if can?(:manager,current_user)
          td = link_to 'Edit', edit_user_path(user)
          td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/new.html.slim
== render 'form'